In [1]:
import torch

In [19]:
a = torch.randn(128,100)
a=a.sum(1, keepdim=True)
a

tensor([[  4.5004],
        [  8.7217],
        [  6.5698],
        [ 18.5326],
        [  1.7922],
        [ -0.6899],
        [-16.2565],
        [ 11.3735],
        [  8.4511],
        [-15.2433],
        [ 13.2229],
        [  9.5448],
        [ 12.0866],
        [ 16.3590],
        [ 10.2108],
        [ 12.1314],
        [  5.9925],
        [  3.7121],
        [ -2.7873],
        [  8.3960],
        [-14.9216],
        [  0.4216],
        [ -6.2077],
        [ -7.1230],
        [ -3.7028],
        [ 12.2746],
        [ -8.5241],
        [ -9.0688],
        [  9.5099],
        [  3.5578],
        [ -2.0885],
        [ -4.6472],
        [ -0.9335],
        [ -3.5896],
        [ -3.0269],
        [ -9.5054],
        [  0.4226],
        [  3.4407],
        [ -7.8164],
        [ -2.4512],
        [ -1.1336],
        [-30.1666],
        [ -7.3180],
        [  4.6407],
        [  3.0844],
        [ -8.0818],
        [ 13.5902],
        [  1.6357],
        [  8.9876],
        [ -0.8477],


In [13]:
b = (torch.randn(128,100)>2).float()
b

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.]])

In [23]:
c=a*b
c.shape

torch.Size([128, 100])

In [30]:
d=c.sum(dim=0)
d.shape

torch.Size([100])

In [31]:
d

tensor([-2.5466e+00,  1.8533e+01,  1.8432e+01, -2.7983e+01,  1.5714e+01,
         1.1583e+00,  4.1410e+01, -5.6560e-01, -2.2858e+01,  1.7964e+01,
         7.9375e+00, -9.1301e+00,  0.0000e+00,  4.7414e+01,  5.6994e+00,
        -1.1540e+01,  5.1006e+00,  7.8300e+00, -7.7180e+00, -1.1336e+00,
        -2.1920e+00, -8.6061e+00,  2.9859e-01,  1.2243e+00, -1.5991e+01,
        -7.8164e+00,  1.2296e+01,  1.1087e+01,  7.3256e+00,  3.9449e+00,
        -1.8863e+00,  1.2653e+01, -3.5896e+00,  2.8828e+01, -6.9108e+00,
         1.2147e+01, -5.8974e+00,  5.5756e+00,  2.3515e+01, -6.0174e+00,
        -4.8370e+01,  3.1120e+01, -1.4158e+01, -8.1864e+00,  9.5508e+00,
        -7.8707e+00,  1.7893e+01, -1.5325e+01,  3.1314e+00, -1.6473e+01,
        -4.1493e+00,  2.4526e+00,  4.0563e+00,  0.0000e+00,  0.0000e+00,
        -2.4358e+00, -3.6598e+01,  2.6875e+01,  1.7922e+00, -1.5286e+01,
         1.0211e+01,  1.6716e-01, -4.5585e-01,  1.6359e+01,  2.0891e+00,
        -2.2783e+01,  3.4407e+00, -7.3180e+00,  1.5